default_language_version:
    python: python3.12
default_stages: [commit, merge-commit, push]
fail_fast: false
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        args: [--profile=black]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=5000]
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.(prj|cpg)$
      - id: fix-encoding-pragma
        args: [--remove]
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--toml-config=eya_def_tools/pyproject.toml]
        additional_dependencies: [
          Flake8-pyproject==1.2.3,
          flake8-pytest-style==2.0.0,
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args: [--config-file=eya_def_tools/pyproject.toml]
        additional_dependencies: [
          email-validator~=2.2.0,
          jsonschema~=4.23.0,
          pandas~=2.2.2,
          pandas-stubs~=2.2.2.240603,
          pycountry~=24.6.1,
          pydantic~=2.8.2,
          pyproj~=3.6.1,
          pytest~=8.3.2,
          ruamel.yaml~=0.18.6,
          sortedcontainers-pydantic~=1.0.0,
          types-jsonschema~=4.23.0.20240712,
        ]
        exclude: |
            (?x)
            ^eya_def_tools/eya_def_tools/utils/doc_utils/data_model_graphics.py$
            |^eya_def_tools/eya_def_tools/utils/doc_utils/eya_def_erdantic.py$
