default_language_version:
    python: python3.12
default_stages: [pre-commit, pre-merge-commit, pre-push]
fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=5000]
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.(prj|cpg)$
      - id: fix-encoding-pragma
        args: [--remove]
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--config-file=eya_def_tools/pyproject.toml]
        additional_dependencies: [
          email-validator==2.2.0,
          jsonschema==4.23.0,
          pandas==2.2.3,
          pandas-stubs==2.2.3.241126,
          pycountry==24.6.1,
          pydantic==2.10.6,
          pyproj==3.7.0,
          pytest==8.3.4,
          ruamel.yaml==0.18.10,
          sortedcontainers==2.4.0,
          sortedcontainers-pydantic==1.0.0,
          types-jsonschema==4.23.0.20241208,
        ]
        exclude: |
            (?x)
            data_model_graphics.py$
            |eya_def_erdantic.py$

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
